modLoader="javafml"
loaderVersion="[40,)"
license="AGPL-3.0-only"
issueTrackerURL="https://github.com/Mimickal/Waterworks/issues"
[[mods]]
modId="waterworks"
version="${file.jarVersion}"
displayName="Waterworks"
# TODO updateJSONURL
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/Mimickal/Waterworks"
logoFile= "waterworks.png"
credits="Mimickal"
authors="Mimickal"
displayTest="MATCH_VERSION"
description='''
Waterworks is a mod that changes how water behaves.
Water accumulates when it rains and evaporates when the sun shines. Rain becomes a function of relative humidity.
'''
